#!/bin/bash
##===----------------------------------------------------------------------===##
##
## This source file is part of the Swift open source project
##
## Copyright (c) 2022 Apple Inc. and the Swift project authors
## Licensed under Apache License v2.0 with Runtime Library Exception
##
## See http://swift.org/LICENSE.txt for license information
## See http://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
##
##===----------------------------------------------------------------------===##
set -euo pipefail

print_usage() {
    echo "usage: ${0##*/} [--verbose] <directory>"
}

# Parse arguments until we find '--' or an argument that isn't an option.
until [ $# -eq 0 ]
do
    case "${1}" in
        --verbose) verbose=1; shift;;
        --) shift; break;;
        -*) echo "unknown option: ${1}"; print_usage; exit 1; shift;;
        *) break;;
    esac
done

# Print usage and leave if we don't have exactly one argument.
if [ $# -ne 1 ]; then
    print_usage
    exit 1
fi

# Check that the directory is inside a Git working directory.
if [ $(git -C "${1}" rev-parse --is-inside-work-tree 2> /dev/null) != "true" ]; then
    echo "${1} is not inside a Git working directory"
    exit 1
fi

# Scan the Git log and pick out the contributors
contributors=$(git -C "${1}" log --pretty=format:'- %an <%ae>%n' | sort | uniq)

# Generate the 'CONTRIBUTORS.txt' file.
cat > "${1}/CONTRIBUTORS.txt" <<- EOF
	For the purpose of tracking copyright, this is the list of individuals and
	organizations who have contributed to Swift Package Manager.

	For employees of an organization/company where the copyright of work done
	by employees of that company is held by the company itself, only the company
	needs to be listed here.

	## COPYRIGHT HOLDERS
	- Apple Inc. (all contributors with '@apple.com')

	### Contributors
	${contributors}

	**Updating this list**
	Please do not edit this file manually. It is generated using \`generate_contributors_list.sh\`. If a name is misspelled or appears multiple times, add an entry in the repository's \`.mailmap\` file.
EOF
